# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb7cfd8f44bb9cf565c22bccbcba5f90327023d35a0a34fd6fdda96d651abf75aa83639350e6afeda042750458da567271db85b2c77f1aad3d949f24404f2672

test:
  secret_key_base: 478b4d081ad14a680fff216b12e5ce1aa43ec1cf95e66f8c0d97c4ed195c7262c525fe486b54d12f39bc837393e3b52a36e051251caa9fa38b36cec105c2ea9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
